import { Recipe } from './types';

export const sampleRecipes: Recipe[] = [
  {
    id: 1,
    title: 'Spaghetti Carbonara',
    image: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=800&h=600&fit=crop',
    ingredients: ['pasta', 'eggs', 'bacon', 'parmesan', 'black pepper', 'garlic'],
    cookingTime: 20,
    description: 'A creamy Italian pasta dish with eggs, cheese, and crispy bacon.',
    cuisine: 'Italian',
    difficulty: 'Medium',
    servings: 4,
    diet: [],
    instructions: [
      'Cook pasta according to package directions',
      'Fry bacon until crispy, then set aside',
      'Whisk eggs with grated parmesan',
      'Combine hot pasta with bacon, then mix in egg mixture off heat',
      'Season with black pepper and serve immediately'
    ],
  },
  {
    id: 2,
    title: 'Chicken Stir Fry',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=600&fit=crop',
    ingredients: ['chicken', 'bell peppers', 'soy sauce', 'ginger', 'garlic', 'rice', 'onion'],
    cookingTime: 25,
    description: 'Quick and flavorful chicken stir fry with fresh vegetables.',
    cuisine: 'Asian',
    difficulty: 'Easy',
    servings: 4,
    diet: ['Gluten-free'],
    instructions: [
      'Cut chicken into bite-sized pieces',
      'Heat oil in a wok or large pan',
      'Stir-fry chicken until cooked through',
      'Add vegetables and cook until tender',
      'Add soy sauce and seasonings, serve over rice'
    ],
  },
  {
    id: 3,
    title: 'Beef Tacos',
    image: 'https://images.unsplash.com/photo-1565299585323-38174c0b5e73?w=800&h=600&fit=crop',
    ingredients: ['ground beef', 'tortillas', 'lettuce', 'tomato', 'cheese', 'onion', 'garlic'],
    cookingTime: 15,
    description: 'Delicious Mexican-style tacos with seasoned ground beef.',
    cuisine: 'Mexican',
    difficulty: 'Easy',
    servings: 4,
    diet: [],
    instructions: [
      'Brown ground beef in a pan',
      'Add taco seasoning and cook until fragrant',
      'Warm tortillas in a dry pan',
      'Fill tortillas with beef and toppings',
      'Serve with salsa and sour cream'
    ],
  },
  {
    id: 4,
    title: 'Greek Salad',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop',
    ingredients: ['tomato', 'cucumber', 'onion', 'olives', 'feta cheese', 'olive oil', 'garlic'],
    cookingTime: 10,
    description: 'Fresh Mediterranean salad with feta cheese and olives.',
    cuisine: 'Mediterranean',
    difficulty: 'Easy',
    servings: 4,
    diet: ['Vegetarian', 'Gluten-free'],
    instructions: [
      'Chop tomatoes, cucumber, and onion',
      'Mix vegetables in a large bowl',
      'Add olives and feta cheese',
      'Drizzle with olive oil and lemon juice',
      'Season with salt, pepper, and oregano'
    ],
  },
  {
    id: 5,
    title: 'Pad Thai',
    image: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=800&h=600&fit=crop',
    ingredients: ['rice noodles', 'chicken', 'eggs', 'bean sprouts', 'peanuts', 'lime', 'garlic'],
    cookingTime: 20,
    description: 'Authentic Thai stir-fried noodles with sweet and tangy flavors.',
    cuisine: 'Asian',
    difficulty: 'Medium',
    servings: 2,
    diet: ['Gluten-free'],
    instructions: [
      'Soak rice noodles in warm water until pliable',
      'Stir-fry chicken until cooked',
      'Push chicken aside, scramble eggs in the pan',
      'Add noodles and Pad Thai sauce',
      'Toss with bean sprouts and peanuts, serve with lime'
    ],
  },
  {
    id: 6,
    title: 'Butter Chicken',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=600&fit=crop',
    ingredients: ['chicken', 'tomato', 'onion', 'garlic', 'ginger', 'butter', 'cream', 'rice'],
    cookingTime: 45,
    description: 'Creamy Indian curry with tender chicken in a rich tomato sauce.',
    cuisine: 'Indian',
    difficulty: 'Medium',
    servings: 4,
    diet: ['Gluten-free'],
    instructions: [
      'Marinate chicken in yogurt and spices',
      'Cook chicken until golden',
      'Sauté onions, garlic, and ginger',
      'Add tomatoes and spices, simmer',
      'Add cream and chicken, serve with rice'
    ],
  },
  {
    id: 7,
    title: 'Margherita Pizza',
    image: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=800&h=600&fit=crop',
    ingredients: ['pizza dough', 'tomato', 'mozzarella', 'basil', 'olive oil', 'garlic'],
    cookingTime: 15,
    description: 'Classic Italian pizza with fresh mozzarella and basil.',
    cuisine: 'Italian',
    difficulty: 'Medium',
    servings: 2,
    diet: ['Vegetarian'],
    instructions: [
      'Preheat oven to 475°F',
      'Roll out pizza dough on a baking sheet',
      'Spread tomato sauce, leaving a border',
      'Top with mozzarella and fresh basil',
      'Bake for 12-15 minutes until golden'
    ],
  },
  {
    id: 8,
    title: 'Beef Burger',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&h=600&fit=crop',
    ingredients: ['ground beef', 'burger buns', 'lettuce', 'tomato', 'onion', 'cheese', 'potato'],
    cookingTime: 20,
    description: 'Juicy beef burger with all the classic toppings.',
    cuisine: 'American',
    difficulty: 'Easy',
    servings: 4,
    diet: [],
    instructions: [
      'Form ground beef into patties',
      'Season patties with salt and pepper',
      'Grill or pan-fry until desired doneness',
      'Toast burger buns',
      'Assemble with lettuce, tomato, onion, and cheese'
    ],
  },
  {
    id: 9,
    title: 'Caesar Salad',
    image: 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=800&h=600&fit=crop',
    ingredients: ['romaine lettuce', 'caesar dressing', 'parmesan', 'croutons', 'anchovies', 'garlic'],
    cookingTime: 10,
    description: 'Crisp romaine lettuce with creamy Caesar dressing.',
    cuisine: 'American',
    difficulty: 'Easy',
    servings: 4,
    diet: [],
    instructions: [
      'Wash and chop romaine lettuce',
      'Make Caesar dressing with anchovies and garlic',
      'Toss lettuce with dressing',
      'Top with parmesan and croutons',
      'Serve immediately'
    ],
  },
  {
    id: 10,
    title: 'Fried Rice',
    image: 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&h=600&fit=crop',
    ingredients: ['rice', 'eggs', 'onion', 'garlic', 'soy sauce', 'peas', 'carrots'],
    cookingTime: 15,
    description: 'Classic Asian fried rice with vegetables and scrambled eggs.',
    cuisine: 'Asian',
    difficulty: 'Easy',
    servings: 4,
    diet: ['Vegetarian', 'Gluten-free'],
    instructions: [
      'Cook rice and let cool',
      'Scramble eggs and set aside',
      'Sauté onions and garlic',
      'Add rice and vegetables',
      'Stir in eggs and soy sauce, serve hot'
    ],
  },
];
